# Generated by Django 3.2.9 on 2021-12-14 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inheritance', '0002_myperson_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_place', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inheritance.place')),
                ('name_restaurant', models.CharField(max_length=20)),
                ('serves_pizza', models.BooleanField(default=False)),
                ('serves_pasta', models.BooleanField(default=False)),
            ],
            bases=('inheritance.place',),
        ),
    ]
