# Generated by Django 3.2.9 on 2021-12-14 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inheritance', '0003_place_restaurants'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaurants',
            new_name='Restaurant',
        ),
    ]
