# Generated by Django 3.2.9 on 2021-12-14 09:08

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('color', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('exists', 'exists'), ('non_existent', 'non_existent')], max_length=12)),
            ],
            managers=[
                ('p_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
