# Generated by Django 3.2.9 on 2021-12-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'todo'), ('progress', 'progress'), ('done', 'done')], default='todo', max_length=8),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ManyToManyField(related_name='category', to='todo.Category'),
        ),
    ]
